---
title: "What we made" 
toc: false
---
## October 27th, 2025
DP: Still recovering from the cold. I just made Kraft Mac and Cheese with pre-packaged salad for nostalgia sake.

## October 26th, 2025
DP: Still recovering from the cold. Caitlin made a collard greens coconut curry (accompanied with cilantro and roasted peanuts) with fried tofu covered in tamarind. 

## October 25th, 2025
DP: Volunteered at food pantry. Exhausted and realized I have a cold, not allergies. Leftovers from yesterday.

## October 24th, 2025
DP: I made beautiful black beans that I cooked with chipotle pepper in adobo sauce (seasoned with cumin, cinammon, maple syrup). I was craving fish tacos so Caitlin came home with Trader Joe's fish sticks and plantains. She made salsa and [Sikil Pak](https://www.thesophisticatedcaveman.com/sikil-pak-mayan-inspired-pepita-dip/), but not really? She says she followed the vibes of it. Caitlin and I ate with flour tortillas. Lovely dinner 

## October 23rd, 2025
DP: I made braised tofu, oven roasted broccoli with sesame oil, and fingerling potato that are coated in a sweet soy-sauce/vinegar glaze (new recipe). I generally don't like potato, but Cailtin really loved it. Boo potato.

## October 22nd, 2025
DP: I made pizza dough. Caitlin came home to make a tamarind pizza sauce that is supposed to evoke Indian food (lo†s of cumin). Topped with pickled onions with the dip being Saag Paneer without the Paneer. Grea take on Indian Pizza.

## October 21th, 2025
DP: I made girl dinner. Made some pickled red onion. Added it to tuna to make a tuna salad. Cut up some cucumbers. Put out some sweet peppers and grapes and sliced apples. Made Caitlin pick up some cheese on the way home. Made some soft boiled eggs. Toasted some sourdough. It was a good choice cause Caitlin came home not feeling that hungry and only wanted to snack. 

## October 20th, 2025
DP: Feeling poorly, so Caitlin made cod in the rice cooker with ginger scallion sauce. Also simple stirfried yu-choy. Served with kimchi and seaweed paper.

## October 19th, 2025
DP: Drove back, so Caitlin made her [chili](/posts/chili.qmd)! More meaty due to the textured vegetable protein. Served with cornbread and sweet potatos-yum!

## October 18th, 2025
DP: Caitlin and I drove to southwest New York to stay at her friend's family homestead (It's gonna be an alpaca farm next year!) The host prepared "white people taco night" and I LOVED IT (first time I had it!). As a meat eater, I was able to get ground beef and shredded chicken cooked in sour cream. Seasoned well! I love all the condiments like chopped tomatos, iceberg lettuce, and red onions. Also their homemade salsa was good (They add dried red peppers) and man the pickled jalapenos were bomb. Caitlin's vegeterian so she had her sweet potatos and beans. White people taco night is 10/10.

## October 17th, 2025
DP: Caitlin got out of work early. So we went to a Japanese cafe in Brookline. She got her hand rolls and I got my pork tonkatsu. 

## October 16th, 2025
DP: I made gao baos with fried tofu and wood ear and shitake mix (braised in soy sauce and maple syrup). As condiments: cucumber, ginger-scallion, as well as spicy mayo. The gao baos I brought frozen (much better than my homemade ones). 

## October 15th, 2025
DP: Caitlin made pasta that included *blue cheese and quick-pickled raisins seasoned with allspice*. To finish it, she added raw red onions and soft-boiled eggs. Caitlin was proud to call it [*"The Ploughman's Pasta"*](/posts/pasta_bc_raisin.qmd). The dish was paired with oven-roasted brussel sprouts coated in maple syrup and smoked paprika sauce. For drinks, I mixed home-made kvas with sparkling water and lime juice. 

## October 14th, 2025
DP: We made fried rice. Typical: carrots, onions, garlic, garlic chives, green onions, and eggs. Seasoned generously with soy sauce and a ton of MSG. Served with leftover green beans.

## October 13th, 2025
DP: I made kimchi stew with canned tuna. Paired with frozen green bean, I did a tamarind based sauce. A play on Pad Thai with a generous amount of peanuts and garlic chives. Then I made oatbread which I paired with the new Trader Joe's Mimolette and apple. I was feeling more bread and apple for dinner. Caitlin ate bread, kimchi stew and rice, and cheese in the same bowl.